version: 2
jobs:
  validate-dependencies:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-12-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-12-{{ .Branch }}
            - yarn-cache-12-

      - run: yarn install
      - run:
          name: yarn validate:dependencies
          command: |
            if ! git log --format=oneline -n 1 | grep -q "\[ignore-audit\]"; then
              yarn validate:dependencies
            else
              echo "Skipping audit"
            fi

  validate-all-dependencies:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-12-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-12-{{ .Branch }}
            - yarn-cache-12-

      - run: yarn install
      - run: yarn validate:dependencies
      - run: yarn validate:dev-dependencies

  release:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - '9f:83:07:d5:13:d2:e5:a6:7c:ec:b0:1f:e3:53:46:55'
      - run: mkdir -p ~/.ssh
      - run:
          name: Keyscan Github
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      # Clean working tree, tag, and push
      - run: git config --global user.email "contact@balte.nl"
      - run: git config --global user.name "balte"
      - run:
          name: Determine release type
          command: |
            if ! git log --format=oneline -n 1 | grep -q "\[release\]"; then
              echo "Pre-release"

              COMMIT_TIMESTAMP=$(git log -1 --pretty=format:%ct HEAD)
              COMMIT_DATE=$(date -d @$COMMIT_TIMESTAMP +%Y%m%d-%H%M%S)
              GIT_HASH=$(git rev-parse --short HEAD)

              echo "export RELEASE_ARGS=\"--prerelease nightly-$COMMIT_DATE-$GIT_HASH --skip.changelog --skip.tag --skip.commit\"" >> $BASH_ENV
              echo 'export PUBLISH_ARGS="--tag nightly"' >> $BASH_ENV
              source $BASH_ENV
            else
              echo "Release"
            fi
      - run: yarn release $RELEASE_ARGS
      - run:
          name: Git push
          command: |
            if ! [ "$RELEASE_ARGS" ]; then
              git push --follow-tags origin HEAD
            fi
      # Build and deploy
      - run: yarn install
      - run: yarn build
      - run:
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM with yarn
          command: NEW_VERSION=$(node -p "require('./package.json').version") && yarn publish --access=public --new-version=$NEW_VERSION --network-timeout 100000 $PUBLISH_ARGS

  prerelease:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Check release is desired
          command: |
            if ! git log --format=oneline -n 1 | grep -q "\[publish\]"; then
              echo "Skip"
              circleci-agent step halt
            else
              echo "Publish experimental"
            fi
      - add_ssh_keys:
          fingerprints:
            - '9f:83:07:d5:13:d2:e5:a6:7c:ec:b0:1f:e3:53:46:55'
      - run: mkdir -p ~/.ssh
      - run:
          name: Keyscan Github
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      # Clean working tree, tag, and push
      - run: git config --global user.email "info@superfly.tv"
      - run: git config --global user.name "superflytvab"
      - run:
          name: yarn release
          command: |
            COMMIT_TIMESTAMP=$(git log -1 --pretty=format:%ct HEAD)
            COMMIT_DATE=$(date -d @$COMMIT_TIMESTAMP +%Y%m%d-%H%M%S)
            GIT_HASH=$(git rev-parse --short HEAD)
            PRERELEASE_TAG=nightly-$(echo $CIRCLE_BRANCH | sed -r 's/[^a-z0-9]+/-/gi')
            yarn release --prerelease $PRERELEASE_TAG-$COMMIT_DATE-$GIT_HASH --skip.changelog --skip.tag --skip.commit
      # Build and deploy
      - run: yarn install
      - run: yarn build
      - run:
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM with yarn
          command: NEW_VERSION=$(node -p "require('./package.json').version") && yarn publish --access=public --new-version=$NEW_VERSION --network-timeout 100000 --tag experimental

workflows:
  version: 2
  build-test-publish:
    jobs:
      - validate-all-dependencies:
          filters:
            branches:
              only:
                - master
                - develop
      - validate-dependencies:
          filters:
            branches:
              only:
                - master
                - develop
      - release:
          requires:
            - validate-dependencies
          filters:
            branches:
              only:
                - master
      - prerelease:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore:
                - master
